// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMY-kzXHatfIBZd5iKL8yqL4dFUbM_E0',
    appId: '1:438886009304:web:f7d6a4d8089ae7c7974aad',
    messagingSenderId: '438886009304',
    projectId: 'aidemoclemensha',
    authDomain: 'aidemoclemensha.firebaseapp.com',
    storageBucket: 'aidemoclemensha.firebasestorage.app',
    measurementId: 'G-R6ZJ99MM67',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnZPaOB1C2HNKaNL4mrbsP0mgF8uRDno',
    appId: '1:438886009304:ios:9d15d1062dbd581e974aad',
    messagingSenderId: '438886009304',
    projectId: 'aidemoclemensha',
    storageBucket: 'aidemoclemensha.firebasestorage.app',
    iosBundleId: 'com.example.aishowcaseapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnZPaOB1C2HNKaNL4mrbsP0mgF8uRDno',
    appId: '1:438886009304:ios:9d15d1062dbd581e974aad',
    messagingSenderId: '438886009304',
    projectId: 'aidemoclemensha',
    storageBucket: 'aidemoclemensha.firebasestorage.app',
    iosBundleId: 'com.example.aishowcaseapplication',
  );
}
